### ISSUE TITLE
PCBWay Assembly Can't Locate Pomagtor (RD90_LZH0230529-004_DJ-5PIN_PH2_54) & EastRising(ER-CON0.4-24P)

### ISSUE THREAD

**Issue by xorb22** [jakkra/ZSWatch-HW#2]
I tried ordering the HW PCB and assembly through PCBWay, but upon review by PCBWay, they could not locate the following components. 

33 | X1 | 1 | Pomagtor | RD90_LZH0230529-004_DJ-5PIN_PH2_54 | DOCK | Pomagtor:RD90_LZH0230529-004_DJ-5PIN_PH2_54 | THT | We can find this part number. Please confirm the correct part number.

34 | X8 | 1 | EastRising | ER-CON0.4-24P | OK-24F024-04 | EastRising:ER-CON0.4-24P | SMD | We can find this part number. Please confirm the correct part number.

How can i overcome this?

Thanks

**Comment by jakkra** [comment]
Hi, the first one is a Do not mount, so they should not source it. It's a custom connector I have gotten manufactured for me. the BOM.xls is updated to more clearly state this.

Second one OK-24F024-04 is the correct number and this should be used for sourcing, and they have successfully sourced this part two times for me. Updated the BOM.xls to make it clearer this is the part number.

Fixed in main now https://github.com/jakkra/ZSWatch-HW/commit/0e061375c47cf4ed94781e597d2eb1aed2d0d848

**Comment by xorb22** [comment]
For the custom Pomagtor connector, how can I get it done and assembled on the pcb? Do you instruction for those? 

Thanks

**Comment by jakkra** [comment]
> For the custom Pomagtor connector, how can I get it done and assembled on the pcb? Do you instruction for those?
> 
> Thanks

You need to buy a low profile standard 1.54 mm female pin header and solder on yourself.

**Comment by xorb22** [comment]
Thanks. Any chance you could share which component you used? From where?
Thanks

**Comment by jakkra** [comment]
> Thanks. Any chance you could share which component you used? From where? Thanks

There is not documentation yet for this, you are a bit early, have not had time to write it all. So note this project is not for beginners, at least not right now.

This is the pin header I have used before, it's about 3.6mm heigh. I don't remember where I bought it however and could not find where I bought it. So you will need to search around a bit.

![IMG20231028085222](https://github.com/jakkra/ZSWatch-HW/assets/4318648/5f423488-2332-49b2-a235-9e2c1b5c36d7)

Depending on whwre you live, I may be able to ship one dock connector + cable, but you need to conect me on discord then: jakkra
